baseurl = "https://apitoolkit.io/"
title = "APIToolkit.io: Automatic API Contract Monitoring & Documentation"
theme = "apitoolkit"
languageCode = 'en-us'
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[Params]
mainSections = ["blog"]
intro = true
headline = "APIToolkit"
description = "Automatic API Monitoring and Documentation"
github = "https://github.com/apitoolkit"
twitter = "https://twitter.com/ApiToolkit"
email = "hello@apitoolkit.io"
opengraph = true
shareTwitter = true
dateFormat = "Mon, Jan 2, 2006"
og_image = "/images/og.png"

[blog]
showSummary = true

[Permalinks]
post = "/:filename/"

[markup.goldmark.renderer]
unsafehtml=true
unsafe=true

[sitemap]
